### ISSUE TITLE
Connect the AR-Reshare app to Backend

### ISSUE THREAD

**Issue by artur-varosyan** [spe-uob/2021-ARReshare#144]
The goal is to connect the Android application to the backend API available at https://ar-reshare.herokuapp.com/. 

Here is the list of endpoints connections that may be implemented:
_(Italicized endpoints indicate that at the time of writing, their functionality has not been implemented yet in the backend)_

## Authentication:

- [X] createAccount
- [X] loginAccount
- [X] closeAccount
- [x] modifyAccount
- [x] requestRegeneratedToken
- [x] _requestPasswordReset_
- [x] _executePasswordReset_

## Products:

- [x] getListingByID
- [x] ~~getAccountListingByID~~
- [x] searchAccountListings
- [x] searchListings
- [x] createListing
- [x] modifyListing
- [x] closeListing

## Messaging:

- [x] createConversation
- [x] closeConversation
- [x] sendConversationMessage
- [x] getConversationDescriptors
- [x] getConversationByID

## Account and Preferences:

- [x] getProfileByID
- [x] modifyAccount
- [x] createSavedListing
- [x] searchSavedListings
- [x] deleteSavedListing
- [x] ~~getAccountAddresses~~

## Miscellaneous

- [x] ~~getCategoryDescriptors~~
- [x] ~~getHomePage~~

**Comment by artur-varosyan** [comment]
The loginAccount and createAccount connections have been implemented with pull request #114.

**Comment by artur-varosyan** [comment]
The searchListings endpoint has been connected to with pull request #147.

**Comment by artur-varosyan** [comment]
We have concluded that getHomePage and getCategoryDescriptor endpoints do not need to be called.

**Comment by artur-varosyan** [comment]
Saved listing functionality has now been implemented in the backend by Durham team. _createSavedListing, searchSavedListings, deleteSavedListing_ endpoints can now be called.

**Comment by arfi2212** [comment]
_createSavedListing_ and _deleteSavedListing_ have been connected with pull request #168

**Comment by arfi2212** [comment]
_requestPasswordReset_ and _executePasswordReset_ do not have backend support

**Comment by arfi2212** [comment]
_modifyListing_ and _closeListing_ were connected with pull request #166

**Comment by artur-varosyan** [comment]
Since _closeAccount_ has been implemented with pull request #193, the AR-Reshare mobile app has been now fully connected with the backend.
